### ISSUE TITLE
Confusing name for variable "half_move"

### ISSUE THREAD

**Issue by deven98** [davecom/chess.dart#11]
In the Chess class, the variable name "half_move" is being used as a counter for the 50-move rule. At first sight it seems like half_move is another name for a ply(A half move) and can be easily misunderstood. "half_move" being named to something like drawCounter would be more appropriate in my opinion.

**Comment by davecom** [comment]
That makes sense if it's not used anywhere else in the program. On the other hand, the name is a remnant of the original library that this was ported from, chess.js. It appears it is still called half_move in chess.js. So, changing it may cause some confusion for pulling future changes from chess.js into chess.dart.

**Comment by deven98** [comment]
Makes sense, thank you.
