### ISSUE TITLE
DartPub package giving an error when added as dependency.

### ISSUE THREAD

**Issue by deven98** [davecom/chess.dart#12]
I have a package [flutter_chess_board](https://pub.dartlang.org/packages/flutter_chess_board#-readme-tab-) on DartPub which has chess as a dependency. It worked fine until Dart 2.1.0 was released. After release, pub analysis gives this as an analysis error:

ERR: The current Dart SDK version is 2.1.0-dev.1.0.flutter-69fce633b7.
 
 Because flutter_chess_board depends on chess >=0.0.2 which requires SDK version <2.0.0, version solving failed.

Note: This is my pubspec.yaml dependency line -> 
chess: ">=0.6.4 <0.7.0"

**Comment by davecom** [comment]
Yeah chess.dart has not been updated for Dart 2.0. I am ready to take pull requests to make it and the unit tests compatible. I don't have time in the next couple of weeks to work on this myself though.

**Comment by EDToaster** [comment]
Hi there, it is ok if I just copy the dart file into my project? I just need it for personal use anyway.

**Comment by davecom** [comment]
@EDToaster Shouldn't be an issue if you're using Dart 1. I'm not sure it will function with Dart 2.

**Comment by EDToaster** [comment]
Hi hi! The code does work if you just change the pubspec.yaml to support Dart 2 (not sure about the tests though.)

**Comment by deven98** [comment]
This might be a really silly question, but where exactly is the constraint saying this package is only for <2.0.0? I don't see anything in the pubspec.yaml.

**Comment by davecom** [comment]
Thanks @deven98 I merged it. Now perhaps we can do some testing until we push another package to pub.

**Comment by deven98** [comment]
Can you please push an update as soon as possible? My package is completely unusable with chess 0.6.4 as dependency.

**Comment by davecom** [comment]
@deven98 I just pushed version 0.6.5 to pub. Let me know if you have any issues.
