### ISSUE TITLE
Method pgn() is returning a moves list text with missing termination marker.

### ISSUE THREAD

**Issue by safield** [davecom/chess.dart#15]
I am calling the pgn() method on a board in progress, and the resulting move text is not terminated with the expect * character that denotes an in progress game.

An example of a string that the pgn method is returning is as follows...

"1. d4 d5 2. Qd3 c5 3. e4 "

**Comment by davecom** [comment]
Thanks for reporting this. Can you check if this same behavior is exhibited by the library that this is a port of—https://github.com/jhlywa/chess.js
Thanks!

**Comment by safield** [comment]
Sorry. I have never done Javascript dev.

**Comment by daniel-mf** [comment]
I just verified chess.js and the behavior is the same.
No "*" character at the end for a game in progress.

**Comment by davecom** [comment]
Thanks @daniel-mf. I guess we will close this for now then.
