### ISSUE TITLE
detect pawn promotion

### ISSUE THREAD

**Issue by destiny07** [davecom/chess.dart#18]
Is there currently any support for detecting pawn promotion?

**Comment by davecom** [comment]
You can look through the moves history for a move that was marked as a promotion. See the documentation here from chess.js:
https://github.com/jhlywa/chess.js#moves-options-

**Comment by destiny07** [comment]
> 
> 
> You can look through the moves history for a move that was marked as a promotion. See the documentation here from chess.js:
> https://github.com/jhlywa/chess.js#moves-options-

thanks, I will check that out.
