### ISSUE TITLE
Ng6 notation not working on move

### ISSUE THREAD

**Issue by mono424** [davecom/chess.dart#19]
Ng6 notation not working on move method.
Is possible, this notation will be supported in futur ?

**Comment by davecom** [comment]
Hi @mono424,
Can you post a code sample? I'm not sure what you mean. It's unlikely any additional notation options will be added unless someone contributes a patch.

**Comment by mono424** [comment]
I do not get a move working with the following code:
```
chess.move('Nf6')
```

but it would work in chess.js :)

**Comment by davecom** [comment]
Was this from an opening position? Nf6 is not a valid move in the starting position in chess. I think you are mistaken.
```
void main() {
  Chess chess = new Chess();
  chess.move('Nf3');
  print(chess.ascii);
}
```

Results in

```
   +------------------------+
 8 | r  n  b  q  k  b  n  r |
 7 | p  p  p  p  p  p  p  p |
 6 | .  .  .  .  .  .  .  . |
 5 | .  .  .  .  .  .  .  . |
 4 | .  .  .  .  .  .  .  . |
 3 | .  .  .  .  .  N  .  . |
 2 | P  P  P  P  P  P  P  P |
 1 | R  N  B  Q  K  B  .  R |
   +------------------------+
     a  b  c  d  e  f  g  h
```
