### ISSUE TITLE
please help 

### ISSUE THREAD

**Issue by oooooALIooooo** [davecom/chess.dart#21]
even tho I assign a correct fen always give this error     6th field (move number) must be a positive integer.

**Comment by davecom** [comment]
Please provide some sample code.

**Comment by oooooALIooooo** [comment]
some fens work but many of them not working and give this error 6th field (move number) must be a positive integer.


// this is my code for displaying a chess board 

Chessboard(
                darkSquareColor: kSecondary_color,
                lightSquareColor: kPrimary_color,
                fen:
                    '4rrk1/pbqn1p1p/1p1b2p1/2pp2N1/2P4P/1P4P1/PB2QP2/1B1R1RK1 w - - 1 0',  
                size: size.width * 0.93,
                orientation: widget.isWhiteToMove
                    ? types.Color.WHITE
                    : types.Color.BLACK,)



 //  i think there must be some logical mistak here in chess class


    /* 2nd criterion: move number field is a integer value > 0? */
    int temp = int.parse(tokens[5], onError: (String) => null);
    if (temp != null) {
      if (temp <= 0) {
        return {
          'valid': false,
          'error_number': 2,
          'error': errors[2]
        };
      }
    } else {
      return {
        'valid': false,
        'error_number': 2,
        'error': errors[2]
      };
    }
