### ISSUE TITLE
Headers in PGN

### ISSUE THREAD

**Issue by barvinog** [davecom/chess.dart#22]
Hello, thank you for your chess package.
There's a problem though.

When I do load_pgn, I don't get pgn headers except for Result.
Is it a bug or feature?

**Comment by barvinog** [comment]
I mean White, Black, WhiteElo, BlackElo, Event, Date, etc.

**Comment by davecom** [comment]
Can you provide a code sample? The functionality is meant to mirror chess.js, so you may want to check that project's documentation:
https://github.com/jhlywa/chess.js

**Comment by barvinog** [comment]
Chess chess = Chess();  
 bool res = chess.load_pgn(text);
 print(chess.san_moves());
 print(chess.header);

chess.san_moves() works perfectly,
but chess.header returns only:
{Result: 1-0}

No Black, no White, etc.

Here's the sample PGN file:
[Event "Rated Blitz game"]
[Site "https://lichess.org/wDRlKLTq"]
[Date "2019.07.01"]
[Round "-"]
[White "Flanagan2000"]
[Black "lacsapmg"]
[Result "1-0"]
[BlackElo "2603"]
[BlackRatingDiff "-13"]
[ECO "B50"]
[Opening "Sicilian Defense: Delayed Alapin"]
[Termination "Normal"]
[TimeControl "180+0"]
[UTCDate "2019.07.01"]
[UTCTime "00:00:42"]
[WhiteElo "2578"]
[WhiteRatingDiff "+14"]

1. e4 c5 2. Nf3 d6 3. c3 Nf6 4. h3 g6 5. Bd3 Bg7 6. Bc2 O-O 7. O-O Nc6 8. d4 cxd4 9. cxd4 Nb4 10. Bb3 Nxe4 11. Qe1 Nxa2 12. Rxa2 d5 13. Nc3 Nxc3 14. Qxc3 b6 15. Bf4 Bb7 16. Rfa1 Qd7 17. Rxa7 Rxa7 18. Rxa7 Rc8 19. Qd2 Qb5 20. Rxb7 Qxb3 21. Rxe7 Bf8 22. Re3 Qa2 23. Rc3 Re8 24. Qc2 1-0

**Comment by barvinog** [comment]
Any updates?

**Comment by davecom** [comment]
Hi @barvinog,
I'm probably not going to have a chance to look at this soon. Happy to take pull requests for fixes. Did you get a chance to checkout if the same behavior is exhibited by chess.js which this is a port of, as a I mentioned above?
