### ISSUE TITLE
loadPgn method returns false in some Pgn strings

### ISSUE THREAD

**Issue by hiusanmaz** [davecom/chess.dart#29]
I've a pgn string which has only FEN and SetUp headers.

[FEN "1q3rk1/2p2ppp/8/5N2/8/2PQ4/PP6/1K1R4 w - - 0 1"]
[SetUp "1"]

1. Ne7+ Kh8 2. Qxh7+ Kxh7 3. Rh1#  1-0

As shown on the image I can easily use this pgn in Chess.com's Analysis Part. 

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/33184936/152704165-6e37641f-7f94-46ab-a866-4e17bfe9d26d.png">

I can also download the regular pgn format (you can see on the attached image) for this game from 'Download' part.
<img width="490" alt="image" src="https://user-images.githubusercontent.com/33184936/152702765-86937f3f-35c1-4f31-9079-1369f62721a9.png">

The problem is for these kind of formats when loadPgn method returns always false even if I use the standart pgn format which I get from the Chess.com

I think the main reason is about the **initial board position** because on the Debug section I got a null _'Move'_ variable in line 1467.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/33184936/152702892-96d938a7-22cd-40de-ba13-0d5630ebfff9.png">

**Comment by davecom** [comment]
Solved by #31.
