### ISSUE TITLE
Incorrect Move Generation for Pawn

### ISSUE THREAD

**Issue by Milan-Chabhadiya** [davecom/chess.dart#33]
The moves function within the package generates inaccurate moves for a pawn situated on square e5 in specific scenarios. The issue arises when it produces the following available moves:

    e5 to e6
    e5 to d6 (incorrect move)

Additionally, the function incorrectly permits the pawn to move to d6, resulting in the removal of the pawn on d5 from the board.

Steps to Reproduce the Issue:

    Set up a scenario where either your or your opponent's pawn is already positioned on the 6th row.
    Move a pawn from a neighboring column two steps forward.

This sequence triggers the generation of incorrect moves, including the flawed move from e5 to d6.

Sample fen:
rnbqkbnr/ppp1p1pp/8/3pPp2/8/8/PPPP1PPP/RNBQKBNR w KQkq d6 0 3

![image](https://github.com/davecom/chess.dart/assets/72852444/41fc03c7-6225-42a0-944d-a4458030dd23)

**Comment by davecom** [comment]
Unless I'm missing something, this is correct behavior according to the en passant rule of chess:
https://en.wikipedia.org/wiki/En_passant
