### ISSUE TITLE
DDC Support

### ISSUE THREAD

**Issue by unibeck** [davecom/chess.dart#8]
Hey Dave,
Running pub build --web-compiler=dartdevc while having dependencies: `chess: 0.6.2` will fail. The gist is what pub outputs https://gist.github.com/unibeck/6fd1246fc8444cb6cb8d3cd481413838. Let me know if you need anymore information.

**Comment by davecom** [comment]
Thanks, @unibeck . I won't have time to look into this in the immediate future. If someone wants to post a pull request to fix it, I'd be grateful.

**Comment by unibeck** [comment]
I have the fix, it's super simple. Can you please create a branch that I have access to push too?

**Comment by davecom** [comment]
Feel free to just create a pull request on the main branch.

**Comment by unibeck** [comment]
I can't, `New Pull Request`  button only gives me the option to compare branches `master` and `refactor`. I can't actually create a new pull request

**Comment by davecom** [comment]
You need to first fork the repository on GitHub (so you will have something like unibeck/chess.dart) and then make your changes to your own fork. You will then have the option of creating a pull request from your fork to the main repository.

**Comment by unibeck** [comment]
Alright thanks! I'll have a pull request ready for your review after work today, ~7 PM ET.

**Comment by davecom** [comment]
Thanks for the contribution!
